name: PR Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install Salesforce CLI
      run: |
        npm install -g @salesforce/cli
        sf version
    
    - name: Install sfdx-git-delta
      run: npm install -g sfdx-git-delta
    
    - name: Authenticate to Salesforce
      run: |
        echo "${{ secrets.SALESFORCE_AUTH_URL }}" > authfile
        sf org login sfdx-url --sfdx-url-file authfile --alias production --set-default
        rm authfile
    
    - name: Generate delta packages
      run: |
        mkdir -p deploy
        sgd --to HEAD --from HEAD~1 --output deploy --generate-delta
    
    - name: Deploy to Salesforce
      run: |
        if [ -f "deploy/package/package.xml" ]; then
          echo "Deploying changes..."
          sf project deploy start --manifest deploy/package/package.xml --test-level RunLocalTests --wait 10
        else
          echo "No changes to deploy"
          sf project deploy start --source-dir force-app --test-level RunLocalTests --wait 10
        fi
    
    - name: Run PMD Code Analysis
      run: |
        if [ -f "pmd-ruleset.xml" ]; then
          echo "Running PMD analysis..."
          # PMD analysis would go here if needed
        fi 