name: ✅ Simple Deploy - Property App

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Salesforce CLI
      run: npm install -g @salesforce/cli
      
    - name: Authenticate
      run: |
        echo "${{ secrets.SALESFORCE_AUTH_URL }}" | sf org login sfdx-url --stdin --alias target --set-default
        
    - name: Deploy Simple Property App
      run: |
        echo "🚀 Deploying Simple Property Management App..."
        sf project deploy start --source-dir force-app --target-org target --wait 20
        
    - name: Success
      run: |
        echo "✅ Simple Property App deployed successfully!"
        echo "Check your Salesforce org: https://cloudseek-dev-ed.develop.lightning.force.com" 